# 前端工程模板
- title: 'front-end' 
  list:
    - name: 'smash-template-fe'         # 基础前端工程模板
    - name: 'smash-template-react'      # react前端工程模板
    - name: 'smash-template-vue'        # vue前端工程模板

# node工程模板
- title: 'node'
  list:
    - name: 'smash-template-node'       # 基础node工程模板
    - name: 'smash-template-express'    # express工程模板

# 中间件工程模板
- title: 'middleware'
  list:
    - name: 'smash-template-helloworld' # helloworld中间件模板
