#!/usr/bin/env node

const program = require('commander');
const programmaticSmash = require('.');
const pkg = require('../package.json');
const { version } = pkg;

const updateNotifier = require('update-notifier');
updateNotifier({
  pkg,
  updateCheckInterval: 1000 * 60 * 60 * 24 * 1, // 1 day
}).notify();

// 注册版本号
program.version(version, '-v, --version');

// 注册初始化命令：该命令会在工作目录下生成.smash/task.yml文件
program
  .command('init')
  .description('Create default task config file')
  .action(function() {
    programmaticSmash.init();
  });

// 注册安装模板命令：该命令会在工作目录下安装模板项目
program
  .command('download <template>')
  .alias('d')
  .description('Download <template>')
  .action(function(templateName) {
    programmaticSmash.download(templateName);
  });

// 注册安装中间件命令：该命令会将中间件安装到home目录下的中间件目录
program
  .command('install')
  .alias('i')
  .description('Install middlewares')
  .action(function() {
    programmaticSmash.install();
  });

// 注册run命令：该命令会执行任务里的中间件。
program
  .command('run <task>')
  .alias('r')
  .description('Run <task>')
  .action(function(taskName) {
    programmaticSmash.run(taskName);
  });

program.on('--help', function() {
  console.log('');
  console.log('Examples:');
  console.log('  $ smash init');
  console.log('  $ smash download smash-template-react');
  console.log('  $ smash install');
  console.log('  $ smash run helloworld');
});

program.parse(process.argv);

if (!process.argv.slice(2).length) {
  program.help();
}
if (program.all) {
  process.exit(-1);
}
