name: Node CI

on: [push]

jobs:
  # 测试主包
  test-main:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 9, 10, 11, 12]
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        os: ${{ matrix.os }}
    - name: test-main
      run: |
        npm i -g yarn
        yarn install
        yarn config set ignore-engines true
        node scripts/test-main.js
      env:
        CI: true
