name: windows

on:
  push:
    branches:
      - master

jobs:
  test-main-and-helper:
    strategy:
      matrix:
        # pacote@10.3.1 required node >=10
        # husky@4.2.1 required node >=10
        node-version: [10, 11, 12]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
      # File exists: C:\npm\prefix\yarn.cmd
      # - run: npm i -g yarn
      - run: |
          cd RepoMain
          yarn install
          node scripts/test-main.js
